### ISSUE TITLE
Set behavior settings in config file

### ISSUE THREAD

**Issue by Ashex1** [AHAAAAAAA/PokemonGo-Map#815]
I've been looking at the PRs as they come in and commenting where reasonable and the current process is that if a PR adds a feature that can be configured, an argument is added. This is great but when this configuration has a sane default it is *much* more reasonable to store this in a config file. 

Arguments should be reserved for things a user absolutely must provide such as credentials, api key, and location. When we're looking at things like [search threads](https://github.com/AHAAAAAAA/PokemonGo-Map/pull/810) and [basic auth](https://github.com/AHAAAAAAA/PokemonGo-Map/pull/717) that aren't necessarily being changed at runtime. Additionally would be good to even add things which aren't necessarily dynamic like the credentials so that we're not exposing secrets in the arguments (e.g Docker exposes arguments passed).

We've already got credentials.json for storing gmaps_key and will soon support holding the basic auth user/password. This should definitely be expanded out a little, I'm partial to using YAML instead of json as it's much easier to work with and we can structure it better when looking at settings that require multiple values (like user/pass) with overlapping key names (basic auth user/pass and PGO user/pass).

This recommendation is to avoid "argument sprawl" where the argparse help returns a huge wall of args that don't have proper help documentation.

**Comment by wcastello** [comment]
Agreed, the number of arguments is getting pretty big already.

**Comment by andrew-bolin** [comment]
For credentials, maybe (given your comment re Docker), but otherwise I don't see the problem with arguments. If they have a sane default, the argument is optional...

(Also don't see any reason to change away from json)

**Comment by Ashex1** [comment]
We'd definitely want to be able to specify where the config file resides. 

Regarding changing away from json, the yaml structure offers better readability and ability to insert comments for improved documentation:

```json
{
	"gmaps_key": "",
	"basic_auth": {
		"enabled": "False",
		"user": "pokemon",
		"password": "pokemon"
	},
	"pgo_auth": {
		"type": "ptc",
		"user": "ashketchum",
		"password": "pikachu"
	}
}
```

```yaml
gmaps_key: ""   # Google Maps Javascript API Key
basic_auth:     # Basic Authentication with Flask
    enabled: "False"
    user: "pokemon"
    password: "pokemon"
pgo_auth:       # Authentication with Niantic Servers
    type: "ptc" # Accepted values of ptc or google
    user: "ashketchum"
    password: "pikachu"
```


Plus we're not dealing with curly brackets and other JSON fun. They're both dictionaries so programmatically the behaviour is practically identical.
